### ISSUE TITLE
Starting Gofish 5 in VFP 9 / windows 10 pro

### ISSUE THREAD

**Issue by parios59** [mattslay/GoFish#2]
starting go fish getting an error:
Ole error code 0x800299c4a:Error loading type library/DLL. Ole object is being ignored. Record Number 8.

some help?

**Comment by mattslay** [comment]
I'm sorry, but I have no idea what this error is.
 


-----Original Message-----

**Comment by Uprightguy** [comment]
I have the same issue seems something in the Otree OLE is not registered on my machine.  Any idea what I need to register or download onto my Win 10 machine to eliminate this error?

**Comment by parios815** [comment]
I ended up removing thor and all features - and re-installing...

Resolve issue for me....

**Comment by Uprightguy** [comment]
Thank you I reinstalled foxpro and it seemed to fix the issue.  Now that i think about it I just brought over the drive with foxpro on it from a dead computer and never really installed the foxpro app on this machine just the runtime.
