### ISSUE TITLE
GoFish finds Methods that do not exist anymore

### ISSUE THREAD

**Issue by Kirides** [mattslay/GoFish#6]
While searching for a word like "outlook" i stumbled across multiple Methods and code paths that do not exists in the current version of the application/library.

These Entries exist multiple times.

ex.: 
- myform.loadAll() - timestamp 959663397
- myform.loadAll() - timestamp 959663402
- myform.loadAll() - timestamp 959663426
- myform.loadAll() - timestamp 1299996004
- ... another 2000 matches for different methods that all contain history entries ...

Often they share the same `UniqueId` eg. `_S5U0MA012` but sometimes they don't (maybe because the position changed?)

**Comment by mattslay** [comment]
I can confirm that I have seen this issue myself, however, it is not a GoFish issue, it is a FoxPro issue. If you USE the form (SCX) or class (vcx), (i.e. open the file as a DBF so you can browse the rows), you can search and find yourself that the code is present on some rows in the table, as does does GoFish, therefore it shows the result. However, when you modify the form or vcx in the IDE designer, you do not see the code.

I believe VFP is leaving some old rows behind that it knows are no longer part of the form or class, but GoFish simply searches every row in the table, so it finds them and displays the result.

The way I fixed mine was I used FoxBin2Prg to dump the SCX file to a SC2 code file, then I deleted the SCX and rebuilt it from the SC2 file, and that fixed the issue, meaning, the old rows with the bad code were no longer present, so GF did not see them nor display them.  I have done the same thing with VCX/VC2 many times. I have found the FoxBin2Prg tool to be very reliable in this rebuilding process.

Please report your results here.
